# permissions for end users to edit createkubesnapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: backup-restore-openstack-mfke
    app.kubernetes.io/managed-by: kustomize
  name: createkubesnapshot-editor-role
rules:
- apiGroups:
  - snapshot.mfke.io
  resources:
  - createkubesnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - snapshot.mfke.io
  resources:
  - createkubesnapshots/status
  verbs:
  - get
