# permissions for end users to view pvcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pvc-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: backup-restore-openstack-mfke
    app.kubernetes.io/part-of: backup-restore-openstack-mfke
    app.kubernetes.io/managed-by: kustomize
  name: pvc-viewer-role
rules:
- apiGroups:
  - snapshot.mfke.io
  resources:
  - pvcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - snapshot.mfke.io
  resources:
  - pvcs/status
  verbs:
  - get
